/* Writes the parameter tables in docs/URL-PARAMETERS.md from the SCHEMA in assets/js/config.js, so the
   documentation can never drift from what the display really accepts.
     node --no-warnings tools/params-doc.mjs           rewrite the tables in the document
     node --no-warnings tools/params-doc.mjs --check   exit 1 if the document is out of date (used by the tests) */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { SCHEMA } from '../assets/js/config.js';

const here = dirname(fileURLToPath(import.meta.url));
const DOC = join(here, '..', 'docs', 'URL-PARAMETERS.md');
const START = '<!-- params:start (generated by tools/params-doc.mjs: do not edit by hand) -->';
const END = '<!-- params:end -->';

function values(spec) {
  switch (spec.type) {
    case 'enum': return spec.values.map((v) => '`' + v + '`').join(' · ');
    case 'intenum': return spec.values.map((v) => '`' + v + '`').join(' · ');
    case 'bool': return '`1` / `0`';
    case 'tri': return '`1` / `0`';
    case 'int': return 'whole number ' + spec.min + '–' + spec.max;
    case 'num': return 'number ' + spec.min + '–' + spec.max;
    case 'text': return 'text (up to ' + spec.max + ' characters)';
    case 'list': return 'comma-separated words';
    case 'time': return '`HH:MM` or `off`';
    default: return '';
  }
}
function def(spec) {
  if (spec.key === 'reload') return '`03:30`';
  if (spec.defText) return spec.defText;
  if (spec.def === null) return 'by mode';
  if (Array.isArray(spec.def)) return 'none';
  if (spec.def === '') return 'none';
  if (spec.type === 'bool') return spec.def ? '`1`' : '`0`';
  return '`' + spec.def + '`';
}
function applies(spec) { return spec.modes ? spec.modes.join(', ') : 'all'; }
const esc = (s) => String(s).replace(/\|/g, '\\|');

export function render() {
  const out = [];
  const groups = [];
  SCHEMA.forEach((s) => { if (groups.indexOf(s.group) < 0) groups.push(s.group); });
  groups.forEach((group) => {
    out.push('### ' + group, '', '| Parameter | Values | Default | Applies to | What it does |', '|---|---|---|---|---|');
    SCHEMA.filter((s) => s.group === group).forEach((s) => {
      out.push('| `' + s.key + '` | ' + esc(values(s)) + ' | ' + def(s) + ' | ' + applies(s) + ' | ' + esc(s.desc) + ' |');
    });
    out.push('');
  });
  return out.join('\n');
}

export function updated(text) {
  const a = text.indexOf(START);
  const b = text.indexOf(END);
  if (a < 0 || b < 0 || b < a) throw new Error('markers missing in ' + DOC);
  return text.slice(0, a + START.length) + '\n\n' + render() + '\n' + text.slice(b);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const current = readFileSync(DOC, 'utf8');
  const next = updated(current);
  if (process.argv.indexOf('--check') >= 0) {
    if (next !== current) { console.error('docs/URL-PARAMETERS.md is out of date: run node tools/params-doc.mjs'); process.exit(1); }
    console.log('parameter reference is up to date');
  } else {
    writeFileSync(DOC, next);
    console.log('updated ' + DOC);
  }
}
